trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'  # Specify the Node.js version
    displayName: 'Install Node.js'

  # Install dependencies and build the project
  - script: |
      npm install
      npm run build
    displayName: 'Install dependencies and build'

  # Create .zip file for artifacts
  - script: |
      zip -r $(Build.ArtifactStagingDirectory)/myapp.zip .
    displayName: 'Create .zip file for artifacts'

  # Publish build artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/myapp.zip'  # Path to the .zip file
      artifactName: 'drop'
    displayName: 'Publish Build Artifacts'

stages:
# Build Stage
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'Install dependencies and build'

    - script: |
        zip -r $(Build.ArtifactStagingDirectory)/myapp.zip .
      displayName: 'Create .zip file for artifacts'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/myapp.zip'  # Path to the .zip file
        artifactName: 'drop'
      displayName: 'Publish Build Artifacts'

# Deploy Stage
- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: DeployWeb
    displayName: 'Deploy Job'
    environment: 'your-environment-name'  # Specify your environment name
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
            displayName: 'Download Artifacts'

          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Your Azure Subscription'
              appType: 'webAppLinux'
              WebAppName: 'Your Web App Name'
              packageForLinux: '$(Pipeline.Workspace)/drop/**/*.zip'
            displayName: 'Deploy to Azure Web App'

          - task: Bash@3
            inputs:
              filePath: '$(Pipeline.Workspace)/drop/deploy.sh'
              workingDirectory: '$(Pipeline.Workspace)/drop'
            displayName: 'Run custom deployment script'
