trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'  # Specify the Node.js version
    displayName: 'Install Node.js'

  - powershell: |
      npm install
      npm run build
    displayName: 'Install dependencies and build'

  - powershell: |
      Copy-Item -Path * -Destination $(Build.ArtifactStagingDirectory) -Recurse -Force
    displayName: 'Copy files to artifact staging directory'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'  # Path to the directory
      artifactName: 'drop'
    displayName: 'Publish Build Artifacts'
