trigger:
  - main

pool:
  vmImage: 'windows-latest'

jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '14.x'  # Specify the Node.js version
        displayName: 'Install Node.js'

      - powershell: |
          npm install
          npm run build
        displayName: 'Install dependencies and build'

      - powershell: |
          Add-Type -AssemblyName System.IO.Compression.FileSystem
          $zipPath = "$(Build.ArtifactStagingDirectory)\myapp.zip"
          $sourcePath = "$(Build.SourcesDirectory)"
          
          # List the source directory contents before creating the ZIP file
          Write-Host "Listing source directory contents:"
          Get-ChildItem -Path $sourcePath -Recurse | ForEach-Object { Write-Host $_.FullName }

          # Check if the source path contains any files or directories
          if (-Not (Test-Path $sourcePath)) {
            throw "Source directory does not exist: $sourcePath"
          }

          if (-Not (Get-ChildItem -Path $sourcePath -Recurse)) {
            throw "Source directory is empty: $sourcePath"
          }

          # Create the ZIP file
          [IO.Compression.ZipFile]::CreateFromDirectory($sourcePath, $zipPath)
          
          # Verify the ZIP file was created
          if (-Not (Test-Path $zipPath)) {
            throw "Failed to create ZIP file at path: $zipPath"
          }

          # List the contents of the artifact staging directory
          Write-Host "Listing artifact staging directory contents:"
          Get-ChildItem -Path "$(Build.ArtifactStagingDirectory)" -Recurse | ForEach-Object { Write-Host $_.FullName }
        displayName: 'Create .zip file for artifacts'

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)\myapp.zip'  # Path to the .zip file
          artifactName: 'drop'
        displayName: 'Publish Build Artifacts'

  - job: Deploy
    displayName: 'Deploy Job'
    dependsOn: Build
    pool:
      vmImage: 'windows-latest'
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          artifactName: 'drop'
          downloadPath: '$(Build.ArtifactStagingDirectory)'

      - powershell: |
          Add-Type -AssemblyName System.IO.Compression.FileSystem
          $zipPath = "$(Build.ArtifactStagingDirectory)\myapp.zip"
          $extractPath = "$(Build.ArtifactStagingDirectory)\extracted"

          # Check if ZIP file exists and display the result
          $zipFileExists = Test-Path $zipPath
          Write-Host "Does the ZIP file exist at $zipPath? $zipFileExists"

          # List the artifact staging directory contents before extraction
          Write-Host "Listing artifact staging directory contents before extraction:"
          Get-ChildItem -Path "$(Build.ArtifactStagingDirectory)" -Recurse | ForEach-Object { Write-Host $_.FullName }

          # Verify the ZIP file exists
          if (-Not $zipFileExists) {
            throw "ZIP file does not exist at path: $zipPath"
          }

          # Ensure the extract path exists
          if (-Not (Test-Path $extractPath)) {
            New-Item -Path $extractPath -ItemType Directory -Force
          }

          # Extract the ZIP file to the 'extracted' folder
          [IO.Compression.ZipFile]::ExtractToDirectory($zipPath, $extractPath)

          # List the contents of the extracted directory
          Write-Host "Listing contents of the extracted directory:"
          Get-ChildItem -Path $extractPath -Recurse | ForEach-Object { Write-Host $_.FullName }

          # Move the extracted files to the artifact staging directory
          Get-ChildItem -Path $extractPath -Recurse | ForEach-Object {
              $dest = Join-Path -Path "$(Build.ArtifactStagingDirectory)" -ChildPath $_.FullName.Substring($extractPath.Length).TrimStart("\")
              if ($_.PSIsContainer) {
                  New-Item -Path $dest -ItemType Directory -Force
              } else {
                  Copy-Item -Path $_.FullName -Destination $dest -Force
              }
          }

          # Clean up the extracted folder
          Remove-Item -Path $extractPath -Recurse -Force
        displayName: 'Extract .zip file and prepare files for deployment'

      - task: AzureWebApp@1
        displayName: 'Azure Web App Deploy: DevPasswordReactjs'
        inputs:
          azureSubscription: 'Pay-As-You-Go (21f81236-6acf-452e-84ca-35e5253f63a8)'
          appType: webApp
          appName: DevPasswordReactjs
          package: '$(Build.ArtifactStagingDirectory)'  # Deploy the extracted files
