trigger:
  - main

pool:
  vmImage: 'windows-latest'

jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '14.x'  # Specify the Node.js version
        displayName: 'Install Node.js'

      - powershell: |
          npm install
          npm run build
        displayName: 'Install dependencies and build'

      - powershell: |
          Add-Type -AssemblyName System.IO.Compression.FileSystem
          $zipPath = "$(Build.ArtifactStagingDirectory)\myapp.zip"
          $sourcePath = "$(Build.SourcesDirectory)\path\to\build"

          # Check if the source path contains any files or directories
          if (-Not (Test-Path $sourcePath)) {
            throw "Source directory does not exist: $sourcePath"
          }

          if (-Not (Get-ChildItem -Path $sourcePath -Recurse)) {
            throw "Source directory is empty: $sourcePath"
          }

          # Create the ZIP file from the source directory
          [IO.Compression.ZipFile]::CreateFromDirectory($sourcePath, $zipPath)

          # Verify the ZIP file was created
          if (-Not (Test-Path $zipPath)) {
            throw "Failed to create ZIP file at path: $zipPath"
          }

          # List the contents of the artifact staging directory
          Write-Host "Listing artifact staging directory contents:"
          Get-ChildItem -Path "$(Build.ArtifactStagingDirectory)" -Recurse | ForEach-Object { Write-Host $_.FullName }
        displayName: 'Create .zip file for artifacts'

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)\myapp.zip'  # Path to the .zip file
          artifactName: 'drop'
        displayName: 'Publish Build Artifacts'

  - job: Deploy
    displayName: 'Deploy Job'
    dependsOn: Build
    pool:
      vmImage: 'windows-latest'
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          artifactName: 'drop'
          downloadPath: '$(Build.ArtifactStagingDirectory)'

      - powershell: |
          # Define the path to the .zip file
          $zipPath = "$(Build.ArtifactStagingDirectory)\drop\myapp.zip"

          # Check if the ZIP file exists
          $zipFileExists = Test-Path $zipPath
          Write-Host "Does the ZIP file exist at $zipPath? $zipFileExists"

          # Verify the ZIP file exists before continuing
          if (-Not $zipFileExists) {
            throw "ZIP file does not exist at $zipPath"
          }

          # List the artifact staging directory contents before setting up the deployment
          Write-Host "Listing artifact staging directory contents:"
          Get-ChildItem -Path "$(Build.ArtifactStagingDirectory)" -Recurse | ForEach-Object { Write-Host $_.FullName }
        displayName: 'Verify .zip file existence'

      - task: AzureWebApp@1
        inputs:
          azureSubscription: 'Pay-As-You-Go (21f81236-6acf-452e-84ca-35e5253f63a8)'
          appName: 'Your Web App Name'
          package: '$(Build.ArtifactStagingDirectory)\drop\myapp.zip'
          deploymentMethod: 'zipDeploy'
        displayName: 'Deploy .zip package to Azure Web App'

      - powershell: |
          # Verify that the deployment was successful
          $status = Invoke-RestMethod -Uri "https://$($env:AZURE_WEBAPP_NAME).scm.azurewebsites.net/api/deployments/latest" -Method Get -Headers @{ "Authorization" = "Bearer $($env:AZURE_WEBAPP_DEPLOYMENT_TOKEN)" }
          Write-Host "Deployment status: $($status.status)"
        displayName: 'Verify Deployment Status'
        env:
          AZURE_WEBAPP_NAME: 'Your Web App Name'
          AZURE_WEBAPP_DEPLOYMENT_TOKEN: $(AzureWebAppDeployToken)
