trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
# Build Stage
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'  # Specify the Node.js version
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'Install dependencies and build'

    - script: |
        zip -r $(Build.ArtifactStagingDirectory)/myapp.zip .
      displayName: 'Create .zip file for artifacts'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/myapp.zip'  # Path to the .zip file
        artifactName: 'drop'
      displayName: 'Publish Build Artifacts'

# Deploy Stage
- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: DeployWeb
    displayName: 'Deploy Job'
    environment: 'development'  # Specify your environment name
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
            displayName: 'Download Artifacts'

          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Pay-As-You-Go (21f81236-6acf-452e-84ca-35e5253f63a8)'
              appType: 'webAppLinux'
              WebAppName: 'DevPasswordReactjs'
              packageForLinux: '$(Pipeline.Workspace)/drop/**/*.zip'
            displayName: 'Deploy to Azure Development Web App'

 # Remove the Bash task if not needed
          # - task: Bash@3
          #   inputs:
          #     targetType: 'inline'
          #     script: |
          #       cd $HOME/site/wwwroot
          #       echo "Installing Node.js packages..."
          #       npm install
          #       echo "Building React application..."
          #       npm run build
          #   displayName: 'Run custom deployment script'
